

DROP DATABASE IF EXISTS superhero;
CREATE DATABASE superhero;
USE superhero; 

CREATE TABLE City (
	CITY_NAME VARCHAR(255),
    CITY_ID int,
    PRIMARY KEY(CITY_ID)
    );

CREATE TABLE Superhero (
	SUPERHERO_ID INT AUTO_INCREMENT,
    SUPERHERO_NAME VARCHAR(255) NOT NULL,
    REEL_NAME VARCHAR(255) NOT NULL,
    IS_HUMAN BOOLEAN NOT NULL,
    CREATION_YEAR INT NOT NULL, 
    POWERLEVEL DECIMAL NOT NULL,
    CITY_ID int,
    PRIMARY KEY(SUPERHERO_ID),
    FOREIGN KEY (city_id) REFERENCES city(city_id));
    
CREATE TABLE Superpower (
	SUPERPOWER_NAME VARCHAR(255),
    SUPERPOWER_ID INT,
    PRIMARY KEY(SUPERPOWER_ID)
    );
    
CREATE TABLE SuperheroPower (
    SUPERHERO_ID int, 
    SUPERPOWER_ID int,
    FOREIGN KEY(SUPERHERO_ID) REFERENCES superhero(SUPERHERO_ID),
    FOREIGN KEY(SUPERPOWER_ID) REFERENCES superpower(SUPERPOWER_ID)
    );



    
    

    









    

    

    